# Generated by Django 4.1.4 on 2023-08-14 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/authors/')),
                ('cloudpicture', models.CharField(blank=True, max_length=10000, null=True)),
                ('description', models.TextField(blank=True)),
                ('facebook', models.CharField(blank=True, max_length=50000, null=True)),
                ('discord', models.CharField(blank=True, max_length=50000, null=True)),
                ('telegram', models.CharField(blank=True, max_length=50000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/categories/')),
                ('cloudpicture', models.CharField(blank=True, max_length=3000)),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/articles/')),
                ('cloudpicture', models.CharField(blank=True, max_length=3000)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True)),
                ('sendmail', models.BooleanField(default=True)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.category')),
            ],
        ),
    ]
