# Generated by Django 4.1.4 on 2023-08-16 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_newsletter_alter_article_created_at_tag_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.CreateModel(
            name='SousArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(max_length=300)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/articles/')),
                ('cloudpicture', models.CharField(blank=True, max_length=3000)),
                ('description', models.TextField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
            ],
        ),
    ]
