# Generated by Django 4.1.4 on 2023-08-18 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_newsletter_email_sousarticle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='discord',
            new_name='twitter',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='telegram',
            new_name='whatsapp',
        ),
    ]
